### ISSUE TITLE
Problem with local files

### ISSUE THREAD

**Issue by arnodirlam** [jonathantribouharet/spotify-playlist#1]
Thanks a lot for this great service, it's become a central part of my Spotify use!

I recently noticed that, when I add a local file to the "Remove from Spotify" playlist, the songs in it are not deleted anymore. As soon as I removed it from the list, it worked again. Also note that, when I noticed this, the local song was the first entry in the removal list.

Ideally, local files should be removed from all playlists when I add them to "Remove from Spotify", just like normal songs. The second best option, in my opinion, is to remove all other files from all playlists, and leave only local files untouched. However, the whole issue might not be a big deal whatsoever.

**Comment by jonathantribouharet** [comment]
Hi,
Thank you for the report, I fixed the bug, Spotify doesn't manage local files the same way it does for the rest.
It should work now.

**Comment by arnodirlam** [comment]
Much delayed but very big thank you for your quick response and the great project! 🎉
