### ISSUE TITLE
How do I remove this service?

### ISSUE THREAD

**Issue by MusicGuys** [jonathantribouharet/spotify-playlist#4]
Hi, I found your link to add the songs to the “Remove from Spotify” on a Spotify forum but now that Spotify added an update to make it easier to edit playlists, I no longer need this. I can delete the playlist but it keeps coming back, which is very frustrating. I have tried to play with the settings on https://spotify-playlist.eivo.fr/ but nothing seems to be working. Can you please help me remove this playlist for good?

**Comment by jonathantribouharet** [comment]
Hi,
I just released a fix, you are just supposed to go on "https://spotify-playlist.eivo.fr/" and click on "connect" and then click on "disconnect".
If it still doesn't work, you can go on your Spotify directly and disconnect the app: https://www.spotify.com/fr/account/apps/

**Comment by MusicGuys** [comment]
Thank you so much!
